[package]
name = "adivon"
version = "0.2.3"
authors = ["Shuyu Wang <andelf@gmail.com>"]
description = "Data Structures of daily use: Graph, HashTable, PriorityQueue, Trie, SuffixTree, Rope, SplayTree, SkipList."
homepage = "https://github.com/andelf/rust-adivon"
repository = "https://github.com/andelf/rust-adivon.git"
keywords = [
  "algorithm",
  "book"
]
license = "MIT"



[dependencies]
rand = "*"
vec_map = "*"
quickcheck = "*"
