[package]
name = "adivon"
version = "0.2.5"
authors = ["Shuyu Wang <andelf@gmail.com>"]
description = "Data Structures of daily use: Graph, HashTable, PriorityQueue, Trie, SuffixTree, Rope, SplayTree, SkipList, RedBlackTree."
homepage = "https://github.com/andelf/rust-adivon"
repository = "https://github.com/andelf/rust-adivon.git"
keywords = [
  "algorithm",
  "book"
]
license = "MIT"


[dependencies]
rand = "0.3"
vec_map = "0.6"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"
